version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python and dependencies..."
      - apt-get update
      - apt-get install -y python3 python3-pip
      - pip3 install --upgrade pip
      - pip3 install pyinstaller  # Install pyinstaller
  build:
    commands:
      - echo "Running Python script to generate executable..."
      - pyinstaller --onefile SampleCode.py  # Generate the executable
      - echo "Build process completed! Executable generated."
  post_build:
    commands:
      - echo "Post-build phase started..."
      - echo "Running tests on the generated executable..."
      - cd dist
      - OUTPUT=$(./your_python_file)  # Capture the output of the executable
      - echo "$OUTPUT"
      - EXPECTED_OUTPUT="7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70"
      - if [ "$OUTPUT" != "$EXPECTED_OUTPUT" ]; then
          echo "Test failed: Output does not match expected results.";
          exit 1;
        fi
      - echo "Test passed: Output matches expected results."
      - echo "Preparing files for upload to S3..."
artifacts:
  files:
    - "dist/SampleCode"  # Path to the generated executable (relative to the build environment)
